"""Faithful evidence-centric financial news forecasting prototype."""

from src.evidence_extractor import (
    EXTRACTION_METHOD,
    KEYWORDS,
    KEYWORD_TO_POLARITY,
    NEGATIVE_KEYWORDS,
    POLARITY_TO_DIRECTION,
    POSITIVE_KEYWORDS,
    SUPPORT_SCORES,
    build_evidence_objects,
    build_summary,
    extract_evidence,
    extract_evidence_batch,
    result_to_dict,
    select_primary_evidence_id,
)
from src.evidence_selector import (
    CLASSIFICATION_TABLE,
    DEFAULT_TOP_K,
    EVIDENCE_SELECTOR_FIELDS,
    EvidenceSelectorError,
    OUTPUT_GROUPS,
    REASON_TABLE,
    REQUIRED_INPUT_FIELDS as SELECTOR_REQUIRED_INPUT_FIELDS,
    SELECTION_METHOD,
    VALID_DIRECTIONS as SELECTOR_VALID_DIRECTIONS,
    VALID_PREDICTIONS as SELECTOR_VALID_PREDICTIONS,
    compute_coverage,
    select_evidence,
    select_evidence_batch,
)
from src.forecast_model import (
    CSV_COLUMNS,
    CSV_DEFAULT_PATH,
    ForecastModelError,
    JSON_DEFAULT_PATH,
    MODEL_VERSION,
    OUTPUT_EVIDENCE_LISTS,
    RATIONALE_TEMPLATES,
    VALID_DIRECTIONS as FORECAST_VALID_DIRECTIONS,
    VALID_PREDICTIONS as FORECAST_VALID_PREDICTIONS,
    WARNING_CODES,
    compute_accuracy_and_confusion,
    predict,
    predict_batch,
    predict_without_evidence,
)
from src.retriever import RetrievalResult, TemporalValidationError, retrieve_valid_news

__all__ = [
    # retriever
    "retrieve_valid_news",
    "RetrievalResult",
    "TemporalValidationError",
    # evidence_extractor
    "extract_evidence",
    "extract_evidence_batch",
    "build_evidence_objects",
    "build_summary",
    "select_primary_evidence_id",
    "result_to_dict",
    "POSITIVE_KEYWORDS",
    "NEGATIVE_KEYWORDS",
    "KEYWORDS",
    "KEYWORD_TO_POLARITY",
    "POLARITY_TO_DIRECTION",
    "SUPPORT_SCORES",
    "EXTRACTION_METHOD",
    # evidence_selector (kept at package root for backward compatibility)
    "select_evidence",
    "select_evidence_batch",
    "compute_coverage",
    "EvidenceSelectorError",
    "CLASSIFICATION_TABLE",
    "REASON_TABLE",
    "SELECTION_METHOD",
    "OUTPUT_GROUPS",
    "DEFAULT_TOP_K",
    "EVIDENCE_SELECTOR_FIELDS",
    "SELECTOR_REQUIRED_INPUT_FIELDS",
    "SELECTOR_VALID_PREDICTIONS",
    "SELECTOR_VALID_DIRECTIONS",
    # forecast_model
    "predict",
    "predict_batch",
    "predict_without_evidence",
    "compute_accuracy_and_confusion",
    "ForecastModelError",
    "MODEL_VERSION",
    "FORECAST_VALID_PREDICTIONS",
    "FORECAST_VALID_DIRECTIONS",
    "OUTPUT_EVIDENCE_LISTS",
    "CSV_COLUMNS",
    "CSV_DEFAULT_PATH",
    "JSON_DEFAULT_PATH",
    "RATIONALE_TEMPLATES",
    "WARNING_CODES",
]
